import{app}from'./comfy/index.js';import{SETTER_TYPES,getLink,getGraphAncestors,getGraphDescendants,findSetterByName,findGettersByName,getVisibleSetNames,getSetNameSourceMap,}from'./eclipse-set-get-utils.js';const SET_TYPE='SetNode [Eclipse]';const GET_TYPE='GetNode [Eclipse]';const CATEGORY='\u{1F312} Eclipse/ Primitives';const LGraphNode=LiteGraph.LGraphNode;const _pasteRenameMap=new Map();let _typeColorMap;function setColorAndBgColor(node,type){if(!_typeColorMap){_typeColorMap={'DEFAULT':LGraphCanvas.node_colors.gray,'MODEL':LGraphCanvas.node_colors.blue,'LATENT':LGraphCanvas.node_colors.purple,'VAE':LGraphCanvas.node_colors.red,'WANVAE':LGraphCanvas.node_colors.red,'CONDITIONING':LGraphCanvas.node_colors.brown,'IMAGE':LGraphCanvas.node_colors.pale_blue,'CLIP':LGraphCanvas.node_colors.yellow,'FLOAT':LGraphCanvas.node_colors.green,'MASK':{color:'#1c5715',bgcolor:'#1f401b'},'INT':{color:'#1b4669',bgcolor:'#29699c'},'CONTROL_NET':{color:'#156653',bgcolor:'#1c453b'},'NOISE':{color:'#2e2e2e',bgcolor:'#242121'},'GUIDER':{color:'#3c7878',bgcolor:'#1c453b'},'SAMPLER':{color:'#614a4a',bgcolor:'#3b2c2c'},'SIGMAS':{color:'#485248',bgcolor:'#272e27'},};}
const colors=_typeColorMap[type]||LGraphCanvas.node_colors?.gray;if(colors){node.color=colors.color;node.bgcolor=colors.bgcolor;}}
function autoColor(node,type){if(!app.ui.settings.getSettingValue('Eclipse.SetGetAutoColor'))return;if(type==='*'){node.color=null;node.bgcolor=null;}
else setColorAndBgColor(node,type);}
function showAlert(message){app.extensionManager.toast.add({severity:'warn',summary:'Eclipse Set/Get',detail:`${message}. Most likely you're missing custom nodes`,life:5000,});}
function collectScopedSetNodes(graph,sameGraphOnly){const scopeGraphs=sameGraphOnly?[graph]:getGraphAncestors(graph);const results=[];for(const g of scopeGraphs){if(!g?._nodes)continue;for(const node of g._nodes){if(node.type===SET_TYPE)results.push(node);}}
return results;}
app.registerExtension({name:'Eclipse.SetNode',registerCustomNodes(){class SetNode extends LGraphNode{defaultVisibility=true;serialize_widgets=true;drawConnection=false;currentGetters=null;slotColor='#FFF';canvas=app.canvas;constructor(title){super(title);if(!this.properties){this.properties={previousName:''};}
this.properties['Node name for S&R']='SetNode [Eclipse]';this.properties.showOutputText=SetNode.defaultVisibility;this.isVirtualNode=true;this.addWidget('text','Constant','',()=>{if(!this.graph||app.configuringGraph)return;this.validateName(this.graph);if(this.widgets[0].value!==''){this.title='Set_'+this.widgets[0].value;}
this.update();this.properties.previousName=this.widgets[0].value;},{});this.addInput('*','*');this.addOutput('*','*');}
onConnectionsChange(slotType,slot,isChangeConnect,link_info){if(app.configuringGraph)return;if(slotType===LiteGraph.INPUT&&!isChangeConnect){const outputConnected=this.outputs[0]?.links?.length>0;if(outputConnected){this.inputs[slot].type=this.outputs[0].type;this.inputs[slot].name=this.outputs[0].name;}else{this.inputs[slot].type='*';this.inputs[slot].name='*';this.outputs[0].type='*';this.outputs[0].name='*';this.title='Set';autoColor(this,'*');}
this.update();}
if(slotType===LiteGraph.OUTPUT&&!isChangeConnect){if(this.outputs&&this.outputs[slot]){const inputConnected=this.inputs[0]?.link!=null;if(inputConnected){this.outputs[slot].type=this.inputs[0].type;this.outputs[slot].name=this.inputs[0].name;}else{this.inputs[0].type='*';this.inputs[0].name='*';this.outputs[slot].type='*';this.outputs[slot].name='*';autoColor(this,'*');}}}
if(link_info&&this.graph&&slotType===LiteGraph.INPUT&&isChangeConnect){const resolve=link_info.resolve(this.graph);const resolvedSlot=resolve?.subgraphInput??resolve?.output;const type=resolvedSlot?.type;if(type){if(this.title==='Set'){this.title='Set_'+type;}
if(this.widgets[0].value===''||this.widgets[0].value==='*'){this.widgets[0].value=type;}
this.validateName(this.graph);this.properties.previousName=this.widgets[0].value;this.inputs[0].type=type;this.inputs[0].name=type;this.outputs[0].type=type;this.outputs[0].name=type;autoColor(this,type);}else{showAlert(`node ${this.title} input undefined.`);}}
if(link_info&&this.graph&&slotType===LiteGraph.OUTPUT&&isChangeConnect){const inputType=this.inputs[0]?.type;if(inputType&&inputType!=='*'){this.outputs[0].type=inputType;this.outputs[0].name=inputType;autoColor(this,inputType);}else{const resolve=link_info.resolve(this.graph);const type=resolve?.input?.type;if(type&&type!=='*'){this.inputs[0].type=type;this.inputs[0].name=type;this.outputs[0].type=type;this.outputs[0].name=type;autoColor(this,type);}}}
this.update();}
validateName(graph,sameGraphOnly){let widgetValue=this.widgets[0].value;if(widgetValue!==''){let tries=0;const existingValues=new Set();const scopedSetNodes=collectScopedSetNodes(graph,sameGraphOnly);scopedSetNodes.forEach(node=>{if(node!==this)existingValues.add(node.widgets[0].value);});const originalValue=widgetValue;const baseName=this._justAdded?widgetValue.replace(/_\d+$/,''):widgetValue;while(existingValues.has(widgetValue)){widgetValue=baseName+'_'+tries;tries++;}
this.widgets[0].value=widgetValue;this.title=widgetValue!==''?'Set_'+widgetValue:'Set';return widgetValue!==originalValue;}
return false;}
clone(){const cloned=super.clone();cloned.inputs[0].name='*';cloned.inputs[0].type='*';cloned.properties.previousName='';cloned.size=cloned.computeSize();return cloned;}
onAdded(){this._justAdded=true;}
onConfigure(){if(this._justAdded&&this.graph&&!app.configuringGraph){const oldName=this.widgets[0].value;this.validateName(this.graph,true);this._justAdded=false;const newName=this.widgets[0].value;if(newName!==oldName){_pasteRenameMap.set(oldName,newName);setTimeout(()=>_pasteRenameMap.delete(oldName),0);}
if(this.inputs[0]?.link==null){this.inputs[0].type='*';this.inputs[0].name='*';this.outputs[0].type='*';this.outputs[0].name='*';this.color=null;this.bgcolor=null;}}
this._justAdded=false;setTimeout(()=>{if(!this.graph)return;const inp=this.inputs?.[0];const out=this.outputs?.[0];if(!inp||!out)return;if(inp.type&&inp.type!=='*'&&out.type&&out.type!=='*')return;if(inp.type&&inp.type!=='*'){out.type=inp.type;out.name=inp.name;autoColor(this,inp.type);this.update();return;}
if(inp.link==null)return;const link=getLink(this.graph,inp.link);if(!link)return;const srcNode=this.graph.getNodeById(link.origin_id);const srcType=srcNode?.outputs?.[link.origin_slot]?.type??link.type;if(srcType&&srcType!=='*'){inp.type=srcType;inp.name=srcType;out.type=srcType;out.name=srcType;autoColor(this,srcType);this.update();}},100);}
update(){if(!this.graph)return;const getters=this.findGetters(this.graph);getters.forEach((getter)=>{getter.setType(this.inputs[0].type);});if(this.widgets[0].value&&this.properties.previousName){const gettersWithPreviousName=this.findGetters(this.graph,true);gettersWithPreviousName.forEach((getter)=>{getter.setName(this.widgets[0].value);});}
app.canvas?.setDirty(true,true);}
findGetters(graph,checkForPreviousName){const name=checkForPreviousName?this.properties.previousName:this.widgets[0].value;if(!name||name==='')return[];return findGettersByName(graph,name,GET_TYPE).map(entry=>entry.node);}
onRemoved(){const allGetters=this.graph._nodes.filter((otherNode)=>otherNode.type===GET_TYPE);allGetters.forEach((otherNode)=>{if(otherNode.setComboValues)otherNode.setComboValues([this]);});}
getExtraMenuOptions(_,options){options.unshift({content:this.drawConnection?'Hide connections':'Show connections',callback:()=>{this.drawConnection=!this.drawConnection;const linkType=this.inputs[0].type;this.slotColor=this.canvas.default_connection_color_byType[linkType];this.canvas.setDirty(true,true);},},{content:'Hide all connections',callback:()=>{for(const n of this.graph._nodes){if(n.type===GET_TYPE||n.type===SET_TYPE)n.drawConnection=false;}
this.canvas.setDirty(true,true);},});this.currentGetters=this.findGetters(this.graph);if(this.currentGetters&&this.currentGetters.length>0){const gettersSubmenu=this.currentGetters.map((getter)=>({content:`${getter.title} id: ${getter.id}`,callback:()=>{this.canvas.centerOnNode(getter);this.canvas.selectNode(getter,false);this.canvas.setDirty(true,true);},}));options.unshift({content:'Getters',has_submenu:true,submenu:{title:'GetNodes',options:gettersSubmenu},});}}
onDrawForeground(ctx,lGraphCanvas){if(this.drawConnection)this._drawVirtualLinks(lGraphCanvas,ctx);}
_drawVirtualLinks(lGraphCanvas,ctx){if(!this.currentGetters?.length)return;const title=this.getTitle?this.getTitle():this.title;const title_width=ctx.measureText(title).width;let start_node_slotpos;if(!this.flags.collapsed){start_node_slotpos=[this.size[0],LiteGraph.NODE_TITLE_HEIGHT*0.5];}else{start_node_slotpos=[title_width+55,-15];}
const defaultLink={type:'default',color:this.slotColor};for(const getter of this.currentGetters){let end_node_slotpos=this.getConnectionPos(false,0);if(!this.flags.collapsed){end_node_slotpos=[getter.pos[0]-end_node_slotpos[0]+this.size[0],getter.pos[1]-end_node_slotpos[1],];}else{end_node_slotpos=[getter.pos[0]-end_node_slotpos[0]+title_width+50,getter.pos[1]-end_node_slotpos[1]-30,];}
lGraphCanvas.renderLink(ctx,start_node_slotpos,end_node_slotpos,defaultLink,false,null,this.slotColor,LiteGraph.RIGHT,LiteGraph.LEFT);}}}
LiteGraph.registerNodeType(SET_TYPE,Object.assign(SetNode,{title:'Set'}));SetNode.category=CATEGORY;},});app.registerExtension({name:'Eclipse.GetNode',registerCustomNodes(){class GetNode extends LGraphNode{defaultVisibility=true;serialize_widgets=true;drawConnection=false;slotColor='#FFF';currentSetter=null;canvas=app.canvas;constructor(title){super(title);if(!this.properties){this.properties={};}
this.properties['Node name for S&R']='GetNode [Eclipse]';this.properties.showOutputText=GetNode.defaultVisibility;this.isVirtualNode=true;const comboOptions={getOptionLabel:(value)=>{if(!value)return'';const source=getSetNameSourceMap().get(value);if(!source||source==='local')return value;return`${value} (${source})`;},};Object.defineProperty(comboOptions,'values',{get:()=>{if(!this.graph)return[];return getVisibleSetNames(this.graph);},enumerable:true,configurable:true,});this.addWidget('combo','Constant','',()=>{if(!app.configuringGraph)this.onRename();},comboOptions);this.addOutput('*','*');}
onConnectionsChange(){if(app.configuringGraph)return;this.validateLinks();}
setName(name){this.widgets[0].value=name;this.onRename();this.serialize();}
onRename(){const setter=this.findSetter(this.graph);if(setter){let linkType=setter.inputs[0].type;this.setType(linkType);this.title='Get_'+setter.widgets[0].value;autoColor(this,linkType);}else{this.setType('*');const name=this.widgets[0].value;this.title=name?'Get_'+name:'Get';}
app.canvas?.setDirty(true,true);}
clone(){const cloned=super.clone();cloned.size=cloned.computeSize();return cloned;}
onAdded(){this._justAdded=true;}
onConfigure(){if(this._justAdded&&!app.configuringGraph){const name=this.widgets[0].value;if(name){const newName=_pasteRenameMap.get(name);if(newName){this.widgets[0].value=newName;}
setTimeout(()=>this.onRename(),0);}}
this._justAdded=false;setTimeout(()=>{if(this.outputs?.[0]?.type&&this.outputs[0].type!=='*')return;this.onRename();},200);}
validateLinks(){if(this.outputs[0].type!=='*'&&this.outputs[0].links&&this.graph){this.outputs[0].links.filter((linkId)=>{const link=getLink(this.graph,linkId);if(!link||!link.type)return false;if(link.type==='*')return false;const targetNode=this.graph.getNodeById(link.target_id);const targetType=targetNode?.inputs?.[link.target_slot]?.type;if(targetType==='*')return false;if(targetType){const targetTypes=String(targetType).split(',');if(targetTypes.includes(this.outputs[0].type))return false;}
return!link.type.split(',').includes(this.outputs[0].type);}).forEach((linkId)=>{this.graph.removeLink(linkId);});}}
setType(type){this.outputs[0].name=type;this.outputs[0].type=type;this.validateLinks();autoColor(this,type);}
findSetter(graph){const name=this.widgets[0].value;const result=findSetterByName(graph,name);return result?result.node:undefined;}
goToSetter(){if(!this.currentSetter)return;const setterGraph=this.currentSetter.graph;if(setterGraph&&setterGraph!==this.graph){this.canvas.setGraph?.(setterGraph);setTimeout(()=>{this.canvas.centerOnNode(this.currentSetter);this.canvas.selectNode(this.currentSetter,false);this.canvas.setDirty(true,true);},0);}else{this.canvas.centerOnNode(this.currentSetter);this.canvas.selectNode(this.currentSetter,false);}}
getInputLink(slot){const name=this.widgets[0].value;if(!name||name==='')return null;const setter=this.graph?._nodes?.find(n=>SETTER_TYPES.has(n.type)&&n.widgets?.[0]?.value===name);if(setter){const slotInfo=setter.inputs[slot];if(!slotInfo||slotInfo.link==null)return null;return getLink(this.graph,slotInfo.link);}
if(name&&!findSetterByName(this.graph,name)){showAlert('No SetNode found for '+name+' ('+this.type+')');}
return null;}
resolveVirtualOutput(slot){const name=this.widgets[0].value;const result=findSetterByName(this.graph,name);if(!result)return undefined;if(result.graph===this.graph)return undefined;const{node:setter,graph:setterGraph}=result;const slotInfo=setter.inputs[slot];if(!slotInfo||slotInfo.link==null)return undefined;const link=getLink(setterGraph,slotInfo.link);if(!link)return undefined;const sourceNode=setterGraph.getNodeById(link.origin_id);if(!sourceNode)return undefined;return{node:sourceNode,slot:link.origin_slot};}
getExtraMenuOptions(_,options){this.currentSetter=this.findSetter(this.graph);if(!this.currentSetter)return;options.unshift({content:'Go to setter',callback:()=>{this.goToSetter();},},{content:this.drawConnection?'Hide connections':'Show connections',callback:()=>{if(!this.currentSetter)return;let linkType=this.currentSetter.inputs[0].type;this.currentSetter.drawConnection=!this.currentSetter.drawConnection;this.currentSetter.slotColor=this.canvas.default_connection_color_byType[linkType];this.drawConnection=this.currentSetter.drawConnection;this.canvas.setDirty(true,true);},});}
onDrawForeground(ctx,lGraphCanvas){if(this.drawConnection)this._drawVirtualLink(lGraphCanvas,ctx);}
_drawVirtualLink(lGraphCanvas,ctx){if(!this.currentSetter)return;const defaultLink={type:'default',color:this.slotColor};let start_node_slotpos=this.currentSetter.getConnectionPos(false,0);start_node_slotpos=[start_node_slotpos[0]-this.pos[0],start_node_slotpos[1]-this.pos[1],];const end_node_slotpos=[0,-LiteGraph.NODE_TITLE_HEIGHT*0.5];lGraphCanvas.renderLink(ctx,start_node_slotpos,end_node_slotpos,defaultLink,false,null,this.slotColor);}}
LiteGraph.registerNodeType(GET_TYPE,Object.assign(GetNode,{title:'Get'}));GetNode.category=CATEGORY;},});app.registerExtension({name:'Eclipse.CrossGraphSetGet',setup(){let patched=false;const originalGraphToPrompt=app.graphToPrompt.bind(app);app.graphToPrompt=async function(...args){if(!patched){try{const subgraphNode=app.graph._nodes.find(n=>typeof n.getInnerNodes==='function');if(subgraphNode){const tempMap=new Map();const dtos=subgraphNode.getInnerNodes(tempMap,[]);if(dtos.length>0){const proto=Object.getPrototypeOf(dtos[0]);const nativeSource=proto.resolveOutput.toString();const hasNativeSupport=nativeSource.includes('resolveVirtualOutput');if(!hasNativeSupport){const DtoClass=proto.constructor;const origResolveOutput=proto.resolveOutput;proto.resolveOutput=function(slot,type,visited){if(typeof this.node?.resolveVirtualOutput==='function'){const virtualSource=this.node.resolveVirtualOutput(slot);if(virtualSource){const inputNodeDto=[...this.nodesByExecutionId.values()].find(dto=>dto instanceof DtoClass&&dto.node===virtualSource.node);if(inputNodeDto){return inputNodeDto.resolveOutput(virtualSource.slot,type,visited);}
throw new Error(`Eclipse: No DTO found for cross-graph source node [${virtualSource.node.id}]`);}}
return origResolveOutput.call(this,slot,type,visited);};}
patched=true;}}}catch(e){console.warn('[Eclipse] Failed to probe ExecutableNodeDTO for cross-graph patch:',e);}}
return originalGraphToPrompt(...args);};},});