import{app,ComfyWidgets}from'./comfy/index.js';import{notifyVue,isVueMode}from'./eclipse-widget-performance-utils.js';import{storeQueuedSeed,enterGraphToPromptHook,exitGraphToPromptHook,getGraphNodeList,clearNodeQueuedSeed,findWorkflowNode}from'./eclipse-seed-utils.js';const LAST_SEED_BUTTON_LABEL='♻️ (Use Last Queued Seed)';const SPECIAL_SEED_RANDOM=-1;const SPECIAL_SEED_INCREMENT=-2;const SPECIAL_SEED_DECREMENT=-3;const SPECIAL_SEEDS=[-1,-2,-3];const nodeLastSeeds={};const SEED_NODE_TYPES=['Seed [Eclipse]','Seed 32-bit [Eclipse]','Sampler Settings+Seed [Eclipse]','Sampler Settings Small+Seed [Eclipse]','Sampler Settings NI+Seed [Eclipse]','Smart Folder [Eclipse]','Sampler Settings NI+Seed v2.1 [Eclipse]',];app.registerExtension({name:'Eclipse.SamplerSettingsSeed',async beforeRegisterNodeDef(nodeType,nodeData,_app){if(!SEED_NODE_TYPES.includes(nodeData.name))return;const origOnNodeCreated=nodeType.prototype.onNodeCreated;nodeType.prototype.onNodeCreated=function(){const origResult=origOnNodeCreated?origOnNodeCreated.apply(this,arguments):undefined;let seedWidget=null;for(const[widgetIndex,widget]of this.widgets.entries()){const widgetName=(widget.name||'').toString().toLowerCase();const widgetLabel=(widget.label||widget.options?.label||widget.options?.name||'').toString().toLowerCase();const localizedName=(widget.localized_name||'').toString().toLowerCase();if(widgetName==='seed'||widgetLabel==='seed'||localizedName==='seed'){seedWidget=widget;}else if(widgetName==='control_after_generate'){this.widgets.splice(widgetIndex,1);}}
if(!seedWidget){console.warn(`Eclipse: Could not find Seed widget in ${nodeData.name}. Widgets:`,this.widgets.map((w)=>({name:w.name,label:w.label,options:w.options})),);return origResult;}
this._Eclipse_seedWidget=seedWidget;this._Eclipse_lastSeed=undefined;this._Eclipse_randomMin=0;this._Eclipse_randomMax=nodeData.name==='Seed 32-bit [Eclipse]'||nodeData.name==='Smart Folder [Eclipse]'?0xffffffff:Number.MAX_SAFE_INTEGER;this._Eclipse_cachedInputSeed=null;this._Eclipse_cachedResolvedSeed=null;const origCallback=seedWidget.callback;seedWidget.callback=(val)=>{this._Eclipse_cachedInputSeed=null;this._Eclipse_cachedResolvedSeed=null;if(origCallback)return origCallback.call(seedWidget,val);};const seedIndex=this.widgets.indexOf(seedWidget);const randomizeBtn=this.addWidget('button','🎲 Randomize Each Time','',()=>{seedWidget.value=-1;if(seedWidget.callback)seedWidget.callback(-1);},{serialize:false},);const newFixedBtn=this.addWidget('button','🎲 New Fixed Random','',()=>{const newSeed=this.generateRandomSeed();seedWidget.value=newSeed;if(seedWidget.callback)seedWidget.callback(newSeed);},{serialize:false},);const lastSeedBtn=this.addWidget('button',LAST_SEED_BUTTON_LABEL,'',()=>{if(this._Eclipse_lastSeed!=null){seedWidget.value=this._Eclipse_lastSeed;lastSeedBtn.name=LAST_SEED_BUTTON_LABEL;lastSeedBtn.disabled=true;if(isVueMode())notifyVue(this);}},{serialize:false},);lastSeedBtn.disabled=true;this._Eclipse_lastSeedButton=lastSeedBtn;const buttons=[randomizeBtn,newFixedBtn,lastSeedBtn];for(let idx=buttons.length-1;idx>=0;idx--){const btn=buttons[idx];const btnIndex=this.widgets.indexOf(btn);if(btnIndex!==seedIndex+1){this.widgets.splice(btnIndex,1);this.widgets.splice(seedIndex+1,0,btn);}}
return origResult;};nodeType.prototype.generateRandomSeed=function(){const step=this._Eclipse_seedWidget?.options?.step||1;const minVal=this._Eclipse_randomMin||0;const range=((this._Eclipse_randomMax||0xffffffff)-minVal)/(step/10);let result=Math.floor(Math.random()*range)*(step/10)+minVal;if(SPECIAL_SEEDS.includes(result))result=0;return result;};nodeType.prototype.getSeedToUse=function(){const seedValue=Number(this._Eclipse_seedWidget.value);if(this._Eclipse_cachedInputSeed===seedValue&&this._Eclipse_cachedResolvedSeed!=null){return this._Eclipse_cachedResolvedSeed;}
let resolved=null;if(SPECIAL_SEEDS.includes(seedValue)){if(typeof this._Eclipse_lastSeed==='number'&&!SPECIAL_SEEDS.includes(this._Eclipse_lastSeed)){if(seedValue===-2){resolved=this._Eclipse_lastSeed+1;}else if(seedValue===-3){resolved=this._Eclipse_lastSeed-1;}}
if(resolved==null||SPECIAL_SEEDS.includes(resolved)){resolved=this.generateRandomSeed();}}
const result=resolved!=null?resolved:seedValue;this._Eclipse_cachedInputSeed=seedValue;this._Eclipse_cachedResolvedSeed=result;return result;};const origOnExecuted=nodeType.prototype.onExecuted;nodeType.prototype.onExecuted=function(outputData){const origResult=origOnExecuted?origOnExecuted.apply(this,arguments):undefined;if(outputData&&outputData.seed!==undefined){this._Eclipse_lastSeed=outputData.seed;nodeLastSeeds[this.id]=outputData.seed;}
return origResult;};},async setup(){const origGraphToPrompt=app.graphToPrompt;app.graphToPrompt=async function(){const seedFilter=n=>SEED_NODE_TYPES.includes(n.type)&&n._Eclipse_seedWidget;enterGraphToPromptHook();for(const{node}of getGraphNodeList(app.graph)){if(seedFilter(node))clearNodeQueuedSeed(node);}
let promptData;try{promptData=await origGraphToPrompt.apply(this,arguments);}catch(e){exitGraphToPromptHook();throw e;}
for(const{node,outputKey}of getGraphNodeList(app.graph)){if(!seedFilter(node))continue;if(node.mode===2||node.mode===4)continue;if(!promptData.output||!promptData.output[outputKey])continue;const resolvedSeed=node.getSeedToUse();storeQueuedSeed(node,resolvedSeed);if(promptData.output[outputKey].inputs&&promptData.output[outputKey].inputs.seed!==undefined){const currentSeed=promptData.output[outputKey].inputs.seed;if(Number(currentSeed)!==Number(resolvedSeed)){promptData.output[outputKey].inputs.seed=resolvedSeed;}}
if(Number(node._Eclipse_lastSeed)!==Number(resolvedSeed)){node._Eclipse_lastSeed=resolvedSeed;nodeLastSeeds[node.id]=resolvedSeed;}
node._Eclipse_cachedInputSeed=null;node._Eclipse_cachedResolvedSeed=null;if(node._Eclipse_lastSeedButton){const currentSeedValue=node._Eclipse_seedWidget.value;if(SPECIAL_SEEDS.includes(currentSeedValue)){node._Eclipse_lastSeedButton.name=`♻️ ${resolvedSeed}`;node._Eclipse_lastSeedButton.disabled=false;}else{node._Eclipse_lastSeedButton.name=LAST_SEED_BUTTON_LABEL;node._Eclipse_lastSeedButton.disabled=true;}
if(isVueMode())notifyVue(node);}
if(promptData.workflow){const workflowNode=findWorkflowNode(promptData.workflow,outputKey);if(workflowNode?.widgets_values){const seedWidgetIndex=node.widgets.indexOf(node._Eclipse_seedWidget);if(seedWidgetIndex>=0&&workflowNode.widgets_values[seedWidgetIndex]!==resolvedSeed){workflowNode.widgets_values[seedWidgetIndex]=resolvedSeed;}}}}
exitGraphToPromptHook();return promptData;};},});